---
title: "first-post"
description: |
 In this study, we are interested in testing a tradeoff pattern of stability/flexibility through a task-switching paradigm. Particularly we are interested in the interaction between pre-switch trials cue stimulus intervals (n-1 CSI’s) and no-switch/switch trials (NS/S).
author:
  - name: Sophia Angleton
    url: https://example.com/norajones
date: 2025-02-19
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Firstly, I want to look at the interaction effects between switch trials, or when someone is switching from one task intruction to another, and no-switch trials, or when someone is doing one task repeatedly. I am doing this by looking at switch costs, represented through differences in response time. 


```{r}
#| include: False
library(here)
library(tidyverse)
library(ez)
library(psych)
library(sparkline)
library(readr)
library(ggsignif)
library(car)
library(broom)
library(ggthemes)

PrepSwitch <- read.csv("~/EDLD_652/FInal Blog/_posts/2025-02-19-first-post/PrepSwitch.csv")

head(PrepSwitch)

#clean data 

#removing practice trials from our df
prep <- PrepSwitch %>% 
  filter(practice != 1)

sum_er <- prep %>% #determine 80% accuracy 
  group_by(id) %>% 
summarize(avg_er = mean(error)) %>% 
  print()

sum_er <- sum_er %>% 
  mutate(outlier_er =  (avg_er > 0.20)) %>% 
  print() #2 people fall below 80% accuracy. id 19 and 30. 

#removing those outliers here and adding switch trials and lag trials and incongruencies. 

prep <- prep %>% 
  filter(id != 19, id != 30) %>% 
  mutate(switch = ifelse(task == lag(task,1), "No-switch", "Switch"), 
         lcsi = lag(csi, 1), incongruent = ifelse(numpresent %in% c(1,3,6,8), 0, 1), lincongruent = lag(incongruent,1), lerror = lag(error, 1), lrt = lag(rt, 1)) %>%#lag looks at trial before, need to filter out the first of each block bc nothing to compare
  filter(trial != 1, rt > 200 & rt < 4000)

prep <- prep %>% 
  group_by(id) %>% 
  mutate(alltrials = n()) %>% 
  ungroup() #I noticed there was one subject that only had 229 trials total...

#view(prep)


#aggragation of the parts of our data that we are interesting in seeing

agglag <- prep %>% 
  group_by(id, lcsi, switch) %>% #agg lag groups to then do anova. 
  summarize(rt = mean(rt[error == 0], na.rm = T), 
            error = mean(error, na.rm = T)) 
agglag

agglag2 <- agglag %>% #this is the important thing we want to see in the n-1 trials. looking at pattern of means here 
  group_by(lcsi, switch) %>% 
  summarize(rt = mean(rt, na.rm = T), 
            error = mean(error, na.rm = T)) 
agglag2


#doing our anovas for the agglag aggragates: 

anovart <- ezANOVA(data = agglag ,  
dv = rt, wid = id, within = .(lcsi, switch), type = 3, detailed = T)
anovart

anovaer <- ezANOVA(data = agglag, 
dv = error, wid = id, within = .(lcsi, switch), type = 3, detailed = T)
anovaer
```

```{r}
boxplot <- agglag %>% 
  filter(switch != "NA") %>% 
  ggplot(aes(x = switch, y = rt)) +
  geom_boxplot(fill = "#AABA99") +
  labs(title = "Trial Type On Reaction Time", x = "Trial Type", y= "Reaction Time (msec)")+
  theme_solarized() 
boxplot

plotly::ggplotly()

```


