---
title: "Interaction Plots"
description: |
  I am looking at the interactions between trial type, switch or no-switch, and our two main effect variables, the cue stimulus interval (CSI) of the trial or the congruency of the trial
author:
  - name: Sophia Angleton
    url: https://example.com/norajones
date: 2025-02-19
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
#| include: False
library(here)
library(tidyverse)
library(ez)
library(psych)
library(readr)
library(ggsignif)
library(plotly)
library(ggthemes)
library(patchwork)
PrepSwitch <- read.csv("~/EDLD_652/FInal Blog/_posts/2025-02-19-first-post/PrepSwitch.csv")

#clean data 
theme_set(theme_solarized())
#removing practice trials from our df
prep <- PrepSwitch %>% 
  filter(practice != 1)

sum_er <- prep %>% #determine 80% accuracy 
  group_by(id) %>% 
summarize(avg_er = mean(error)) %>% 
  print()

sum_er <- sum_er %>% 
  mutate(outlier_er =  (avg_er > 0.20)) %>% 
  print() #2 people fall below 80% accuracy. id 19 and 30. 

#removing those outliers here and adding switch trials and lag trials and incongruencies. 

prep <- prep %>% 
  filter(id != 19, id != 30) %>% 
  mutate(switch = ifelse(task == lag(task,1), "No-switch", "Switch"), 
         lcsi = lag(csi, 1), incongruent = ifelse(numpresent %in% c(1,3,6,8), 0, 1), lincongruent = lag(incongruent,1), lerror = lag(error, 1), lrt = lag(rt, 1)) %>%#lag looks at trial before, need to filter out the first of each block bc nothing to compare
  filter(trial != 1, rt > 200 & rt < 4000)

prep <- prep %>% 
  group_by(id) %>% 
  mutate(alltrials = n()) %>% 
  ungroup() #I noticed there was one subject that only had 229 trials total...

#view(prep)

```




```{r}
# Set up the plotting area with two plots side by side
par(mfrow = c(1, 2))

# First interaction plot without the automatic trace label and legend
interaction.plot(x.factor = prep$task,
                 trace.factor = prep$incongruent,
                 response = prep$rt,
                 fun = mean,
                 type = "b",
                 col = c("black", "green"),
                 pch = c(19, 17),
                 fixed = TRUE,
                 trace.label = "",          # Remove trace factor label
                 leg.bty = "o",               # No border for legend
                 xlab = "",         # Custom x-axis label
                 ylab = "Response Time (msec)") # Custom y-axis label

# Add custom legend to the first plot
legend("center", legend = c("Congruent", "Incongruent"), col = c("black", "green"), pch = c(19, 17), bty = "n", cex = .8)
# Manually add the trace label centered above the first plot
mtext("Congruency", side = 3, line = .3, at = mean(par("usr")[1:2]), cex = .9)
# Second interaction plot without the automatic trace label and legend
interaction.plot(x.factor = prep$task,
                 trace.factor = prep$csi,
                 response = prep$rt,
                 fun = mean,
                 type = "b",
                 col = c("black", "red"),
                 pch = c(19, 17),
                 fixed = TRUE,
                 trace.label = "",          # Remove trace factor label
                 leg.bty = "o",               # No border for legend
                 xlab = "",                   # Blank x-axis label
                 ylab = "" 
                 )                   # Blank y-axis label

# Add custom legend to the second plot
legend("center", legend = c("Short CSI", "Long CSI"), col = c("black", "red"), pch = c(19, 17), bty = "n", cex = .8)
mtext("Cue Stimulus Interval", side = 3, line = .3, at = mean(par("usr")[1:2]), cex = .9)

# Manually add the main title centered above both plots
mtext("Interactions Of Congruency and CSI On Trial Type", side = 3, line = 2, at = .4, cex = 1.5)
mtext("Trial Type", side = 1, line = 2, at = .4, cex = 1.2)

# Reset plotting parameters to default
par(mfrow = c(1, 1))

```

